### ISSUE TITLE
Unmarshalling InteractionDataResolved.Members fails

### ISSUE THREAD

**Issue by reifiedbeans** [Amatsagu/Tempest#17]
### Context
Tempest: v1.1.1
Go: v1.21.1

### Issue

Unmarshalling `InteractionDataResolved.Members` fails when parsing Discord interactions similar to the following:
```
"data": {
  "guild_id": "76543210987654321",
  "id": "1151765326615289907",
  "name": "hello",
  "options": [
    {
      "name": "message",
      "type": 3,
      "value": "<@12345678901234567> is great"
    }
  ],
  "resolved": {
    "members": {
      "12345678901234567": {
        "avatar": null,
        "communication_disabled_until": null,
        "flags": 0,
        "joined_at": "2022-01-01T06:21:57.248000+00:00",
        "nick": "Drew",
        "pending": false,
        "permissions": "562949953421311",
        "premium_since": null,
        "roles": [
          "12345678901234568",
          "12345678901234569"
        ],
        "unusual_dm_activity_until": null
      }
    },
    "users": {...}
  },
```

The error that is printed out:
```
json: cannot unmarshal object into Go struct field InteractionDataResolved.Members of type tempest.Snowflake
```

### Investigation

I pulled the code to tinker around. To start, I tried adding `omitempty` to non-existent fields in the [`Member`](https://github.com/Amatsagu/Tempest/blob/64ee2b8dc12128e4f1a33f72ad64ed1474bebf27/target.go#L75) struct, but that did not fix it.

Then, I tried to find a minimal example of this unmarshalling error. I devised a a similar struct pattern, then tried unmarshalling it using `encoding/json`, and [it worked](https://go.dev/play/p/SO-SHVATmt8). I then replaced the stdlib JSON implementation with [goccy/go-json](https://github.com/goccy/go-json) (current JSON marshaller for Tempest), and saw a similar error:

```
panic: json: cannot unmarshal object into Go struct field xxx.Test of type main.Snowflake
```

This makes me think there is an incompatibility with how goccy/go-json is parsing `map`s that use a custom key.

### Suggestions

Seems that there are a few ways to resolve this:

1. Get goccy/go-json to fix their `map` key implementation (Tempest is still broken until this happens though)
2. Switch from goccy/go-json to a different JSON marshalling implementation
3. Change the type for [`InteractionDataResolved`](https://github.com/Amatsagu/Tempest/blob/64ee2b8dc12128e4f1a33f72ad64ed1474bebf27/interaction.go#L105) to be more compatible with goccy/go-json

**Comment by Amatsagu** [comment]
Hey, thanks for info!
I was not aware of this issue until now. I think we'll just ditch `goccy/go-json` at this point.

I've done some benchmarking yesterday with `Client#AwaitComponent` method - spawned up to 20mln listeners with lifetime of 5 minutes & waited for them to close (repeat few times). Using pprof web UI - I found that Tempest lib may have tiny memory leakage but I have no idea what may be the cause of it. Pprof only saw few call frames coming from `goccy/go-json` even after timeout of all listeners.

I have screenshot from earlier test on 100k listeners:
![image](https://github.com/Amatsagu/Tempest/assets/81469656/0e3aa3d1-3713-45a2-8658-84ca67e38694)
![image](https://github.com/Amatsagu/Tempest/assets/81469656/0b1c2cb0-fdbf-48a2-ac20-f40465e81684)
![image](https://github.com/Amatsagu/Tempest/assets/81469656/2af93dd9-bd86-496e-b1f2-2330b235e22e)

Recorded heap allocs that got stuck points to code at https://github.com/Amatsagu/Tempest/blob/master/client-internal-handler.go#L70

I'll continue monitoring it but it seems like all of those bugs start to happen after me trying to replace std json package.

**Comment by Amatsagu** [comment]
Sonnet received an update and they're now working fine on go 1.21^.
Here's update thread: https://github.com/sugawarayuuta/sonnet/issues/7

I've run your example code from https://go.dev/play/p/SO-SHVATmt8 with sonnet and it works just fine. I'll replace current goccy/go-json back to sonnet somewhere in weekend. Feel free to make pull request if you want to have if faster.
