### ISSUE TITLE
Missing Resolved Member in ComponentInteractionData

### ISSUE THREAD

**Issue by chyndman** [amatsagu/tempest#22]
Hi,

I believe `ComponentInteractionData` needs a `Resolved` member to properly unmarshal.

In [interaction.go](https://github.com/Amatsagu/Tempest/blob/f63573f6e890a318ce4512273e2b40c4a2e358bd/interaction.go#L116):

```go
// https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-message-component-data-structure
type ComponentInteractionData struct {
	CustomID string              `json:"custom_id"`
	Type     ComponentType       `json:"component_type"`
	Values   []*SelectMenuOption `json:"values,omitempty"`
}
```

That documentation link shows a `resolved?` member. I'm relatively new to Go and so I didn't really debug this but I saw `bad request` in a response to a command I set up with a User Select component and suspecting [this](https://github.com/Amatsagu/Tempest/blob/v1.1.5/client-internal-handler.go#L75) is the `json.Unmarshal` that's failing.

**Comment by Amatsagu** [comment]
Hey,
It's possible I made mistake.. I won't be able to verify that for next week or two. If that's an important element for Your creation, feel free to make pull request. Just if you decide to do it, please double check if I used correct link to documentation so it's 100% this, sadly Discord API is quite messy and website is run by community which sometimes leads to typos.

**Comment by chyndman** [comment]
OK thanks. I didn't realize the docs were community maintained. I've started initially debugging locally, the unmarshal is failing but possibly for other or additional reasons. When I get something working on my end I'll do a PR.

**Comment by amatsagu** [comment]
Hey, I think I'll be able to work on that in day or two. Could you send me example command/interaction that you worked on which causes this bug? It would greatly help me to target down potential issue.

**Comment by chyndman** [comment]
I actually believe I tracked it down. Sorry I haven't yet replied. The issue at least for select menus is that `Values` should be `[]string` instead of `[]*SelectMenuOption`. You could also add a member for the `resolved?` but that wasn't what was causing my error. You can see discordgo's version has both of these changes in its implementation: https://github.com/bwmarrin/discordgo/blob/afc57886f91a4af3c2ebcc6ac39f1b07138f44ab/interactions.go#L347

If you still would like me to send a PR and/or an example command, let me know.

**Comment by amatsagu** [comment]
Hey, I will study it and push commit if needed but I think it would be nice if you could open pull request. You've found it so I thing you should get credit for it. See it as easy chance for contribution to the project.
