### ISSUE TITLE
Serve and ServeTls methods for Client

### ISSUE THREAD

**Issue by awlsring** [amatsagu/tempest#24]
Hi there,

I started looking at this library and wanted to use it for my current project. I have a specific need to support passing a custom `net.Listener` interface that will be used to listen when launching the HTTP server.

My thinking here is to make two methods `client.Serve` and `client.ServeTls`. These would each have the method signatures of the existing `ListenAndServe` methods, but would also include passing a `net.Listener`.

I'm open to doing the work, just wanted to check if this is inline for the vision of the library.

**Comment by amatsagu** [comment]
Hi,
I have nothing against it, please open a new pull request if you want it to be added.

I remember there was "Hijack" client method that allowed you to completely skip default implementation and work on your own magic but it looks like I had to remove it somewhere in wall of commits... It looked like that:
```go
// Let's you take control over client's life cycle. Please avoid using it unless you want to integrate custom http client.
func (client *Client) Hijack() func(w http.ResponseWriter, r *http.Request) {
	client.running = true
	return client.handleRequest
}
```

It's up to You whether you want to open pull request with `client#Serve` and `client#ServeTLS` and/or bring back `client#Hijack` method. I assume just bringing hijack back might be a better idea... Assuming You'll add serve & serve tls, client will have 4 different methods to start which sounds a bit funny to me but oh well - both ideas are acceptable.

**Comment by awlsring** [comment]
Oh cool, I didn't see that method. I'll try it out first and see if I can get it to work.
