### ISSUE TITLE
Getting 400 http status 

### ISSUE THREAD

**Issue by nicocesar** [amatsagu/tempest#25]
rest.go should have an "||" in line 189  

```
	} else if res.StatusCode < 200 || res.StatusCode > 299 {
		return nil, errors.New(res.Status + " :: " + string(body)), true
	}
```

I'm getting a 400 from Discord API 400 Bad Request :: {\"message\": \"The request body contains invalid JSON.\", \"code\": 50109}"

The error gets discarded silently otherwise

**Comment by amatsagu** [comment]
Hey, you're right. Updated code in [fc4bb99](https://github.com/amatsagu/tempest/commit/fc4bb99791151e84ed2a815a71f9f4cf0fc72a57) commit.

**Comment by amatsagu** [comment]
Closing for now. Feel free to reopen if You think problem was not solved.
