### ISSUE TITLE
Defer for component handlers

### ISSUE THREAD

**Issue by stein-f** [amatsagu/tempest#31]
There seems to be defer support for command handlers but not component handlers. Is it possible to add `Defer` and `SendFollowUp` methods for components?

Thanks

**Comment by amatsagu** [comment]
Hey, sorry for long time with no answer - Could You send me direct link to Discord API docs page where it shows that generic component uses defer and send follow up? I've seen that many smaller changes were done in last few months but as far as I'm aware those methods are basically used on slash command interactions only - if there are more uses, I at least never seen it actually in use.

**Comment by stein-f** [comment]
I'm running my own fork with the defer added for components - it's needed if somebody clicks a button and the processing takes some time - in the same way a slash command would work.

I simply copied the command code to interactions

```go
// Use to let user/member know that bot is processing command.
// Make ephemeral = true to make notification visible only to target.
func (itx *ComponentInteraction) Defer(ephemeral bool) error {
	var flags uint64 = 0

	if ephemeral {
		flags = 64 // Ephemeral flag
	}

	// Construct the request to Discord API
	_, err := itx.Client.Rest.Request(http.MethodPost, "/interactions/"+itx.ID.String()+"/"+itx.Token+"/callback", ResponseMessage{
		Type: DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE_RESPONSE_TYPE, // 5
		Data: &ResponseMessageData{
			Flags: flags,
		},
	})

	return err
}

// SendFollowUp sends a follow-up message after a component interaction has been deferred.
// If ephemeral is set to true, the message will be visible only to the user who triggered the interaction.
func (itx *ComponentInteraction) SendFollowUp(content ResponseMessageData, ephemeral bool) (Message, error) {
	if ephemeral && content.Flags == 0 {
		content.Flags = 64 // Ephemeral flag
	}

	// Send a POST request to Discord's webhook endpoint for follow-up messages
	raw, err := itx.Client.Rest.Request(http.MethodPost, "/webhooks/"+itx.ApplicationID.String()+"/"+itx.Token, content)
	if err != nil {
		return Message{}, err
	}

	// Unmarshal the response into a Message struct
	res := Message{}
	err = sonnet.Unmarshal(raw, &res)
	if err != nil {
		return Message{}, errors.New("failed to parse received data from discord")
	}

	return res, nil
}

```

**Comment by amatsagu** [comment]
About that - your higher code may be working but I don't think it's intended to work this way?
When comes to components - you're supposed to return your intention as fast as possible, ideally when responding to http request. So, you can defer buttons or select menus this way:
```go
func (itx ComponentInteraction) AcknowledgeWithDefer(ephemeral bool) error {
	var flags uint64 = 0

	if ephemeral {
		flags = 64
	}

	body, err := json.Marshal(ResponseMessage{
		Type: DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE_RESPONSE_TYPE,
		Data: &ResponseMessageData{
			Flags: flags,
		},
	})

	itx.w.Header().Add("Content-Type", CONTENT_TYPE_JSON)
	itx.w.Write(body)
	return err
}
```

That works, problem is with follow up - it'll error because component/webhook no longer exist - your component id is no longer valid.
![latest-screenshot](https://github.com/user-attachments/assets/71e87a56-e915-4e1a-9914-d20f4fc0ede9)
![latest-screenshot](https://github.com/user-attachments/assets/af537bf2-e08e-4153-86ee-a3bf0a29dd84)

**Comment by amatsagu** [comment]
I'll wait for more ideas if you have any. Good workaround for now would be to just acknowledge button instantly with nothing and create ephemeral message that replies to initial slash command reply saying like "# {bot} is thinking..." and then just edit this message when you're ready. It should look almost identical (minus those 3 thinking dots animation, unless you'll add own emojis) and can work anytime - is not limited to first 15min reply window.

**Comment by amatsagu** [comment]
I would like to solve this issue but I don't see any clear way for now. I want to avoid relying on basically hacks like you did. While your trick works today - discord can make update to it at any time, without any notification. My higher idea should be basically indistinguishable from regular defer mechanic. You can add "-#" at beginning to make text smaller and in gray color. I hope this works for you, feel free to open new issue if you'll find proper solution.
![latest-screenshot](https://github.com/user-attachments/assets/49dc956d-f5b8-4851-abe3-1c291331e790)
