### ISSUE TITLE
Accessing `Client` inside different types of interactions

### ISSUE THREAD

**Issue by danprince** [amatsagu/tempest#33]
👋 Hey and thanks for Tempest!

I've noticed that some of the interaction structs have a `Client` key that isn't set during the interaction callbacks.

For example, for `ComponentInteraction`, the `Client` is attached to the interaction here:

https://github.com/amatsagu/tempest/blob/c097fa4fc3c577e77fe58d15bf7da69af7c97be3/client-handler.go#L83

Compare to `CommandInteraction` and `ModalInteraction` where `itx.Client` is `nil` in the corresponding handlers.

I'm not sure whether this is by design, but it _looks_ like it would be possible to provide the client for the other interaction types by setting `itx.Client` in the other switch cases too. Would you accept a PR for that?

My current workaround inside my modal submit handler is just to create a brand new client with `NewClient` so that I can send multiple messages in response to the modal submission.

**Comment by amatsagu** [comment]
Sure thing! I don't really remember why I've done it the way it is but your suggestion sounds logical so let's go with that. I'm currently short on time so if you want to make a PR, I would appreciate it.

This lib was first project I've made from A to Z using Go, back then I was still new to idea of goroutines, channels, etc. so some parts of code are made to just work but I understand they may look weird as they do not follow any "good patterns".

**Comment by danprince** [comment]
> This lib was first project I've made from A to Z using Go, back then I was still new to idea of goroutines, channels, etc. so some parts of code are made to just work but I understand they may look weird as they do not follow any "good patterns".

😄 Been there myself many times! Thanks for the super quick response. PR is over at #34.
